@startuml
|#AntiqueWhite|教务处|
start
:建立课程;
:课表]
|#AntiqueWhite|教师|
:安排教师;
|#AntiqueWhite|教务处|
:开设课程;
|#AntiqueWhite|学生|
:选课;
|教师|
:安排平时实验;
:发布实验内容;
|学生|
:完成并上交实验;
|教师|
:批改实验;
'|#AntiqueWhite|系统|
':记录分数并且求取平均值;
|学生|
:查询实验分数;

stop

@enduml