@startuml

class teacher_bean {
姓名
性别
职工编号
职称
电话
邮箱
{abstract}
set_work()
correct_work()
}

class student_bean{
姓名
学号
性别
专业
年级
班级
平均成绩
{abstract}
select_work()
upload_work()
check_work()
}

class class_bean{
课程号
课程名
学年
学期
}

class experiment_bean{
实验序号
实验名称
实验内容
实验成绩
实验评价
}

class academy_bean{
学院
主任
电话
邮箱
{abstract}
set_class()
}

class user_bean{
用户ID
真实姓名
github姓名
密码
}

student_bean "1" --> "N" experiment_bean :完成实验内容
teacher_bean "1" --> "N" experiment_bean :批改实验，安排实验
student_bean "N" --> "N" class_bean :选课
teacher_bean "1" --> "N" class_bean :任课
class_bean "1" -- "N" experiment_bean
academy_bean "1" --> "N" class_bean :建立课程
academy_bean "1" --> "N" user_bean :管理
teacher_bean "1" --> "N" user_bean
student_bean "1" --> "N" user_bean


@enduml