@startuml
skinparam sequenceArrowThickness 2
skinparam maxmessagesize 60

actor "读者or管理员" as U
participant "系统" as A
participant "书库" as B
participant "书" as C
participant "借书记录" as D
participant "逾期记录" as E

U -> A: 还书
A -> U:读取图书编码
A -> D:查找借阅记录
D -> C:归还书本
C -> B: 修改库存数量
A -> D: 记录归还信息
loop 如果逾期
A-> E:登记逾期记录
end
A->U:还书成功
@enduml